import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "myxellia",
  description: "Generated by create next app",
};

const euclid = localFont({
  src: [
    {
      path: "./fonts/Euclid-Circular-B-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Euclid-Circular-B-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Euclid-Circular-B-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Euclid-Circular-B-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Euclid-Circular-B-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        data-new-gr-c-s-check-loaded="14.1248.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
        className={euclid.className}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
