import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "myxellia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        data-new-gr-c-s-check-loaded="14.1248.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
